-- Company registration schema
-- Compatible with H2 2.x and PostgreSQL 10+.
-- Reference data: run db/ddl/data.sql after this script.
-- Tear-down: run db/ddl/drop.sql to drop all tables (then schema.sql + data.sql to recreate).
-- Clear data only: run db/ddl/clean-data.sql (then data.sql to reseed reference rows).

CREATE TABLE clients (
    client_id VARCHAR(255) NOT NULL PRIMARY KEY,
    api_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_clients_api_key UNIQUE (api_key)
);

-- company related tables --
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_companies_registration_number UNIQUE (registration_number),
    CONSTRAINT chk_companies_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- Enforces unique company name among ACTIVE rows only (INACTIVE names may be reused).
-- Also serves as the lookup index for exact name checks (WHERE name = ? AND status = 'ACTIVE');
-- no additional index on name or (name, status) is required.
CREATE UNIQUE INDEX uk_companies_name_active
    ON companies (name)
    WHERE status = 'ACTIVE';

CREATE TABLE company_name_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_company_name_history_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
);
-- company related tables --


-- registration request related tables --
CREATE TABLE registration_request_statuses (
    code VARCHAR(32) NOT NULL PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL,
    terminal BOOLEAN NOT NULL
);

CREATE TABLE registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL,
    client_request_id VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    company_id BIGINT,
    error_message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_registration_requests_client_client_request_id
        UNIQUE (client_id, client_request_id),
    CONSTRAINT fk_registration_requests_client
        FOREIGN KEY (client_id) REFERENCES clients (client_id),
    CONSTRAINT fk_registration_requests_status
        FOREIGN KEY (status_code) REFERENCES registration_request_statuses (code),
    CONSTRAINT fk_registration_requests_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
);

-- Supports scheduled job: oldest PENDING request per registration_number (any client), processed in created_at order.
-- Not scoped to client_id — concurrent submits for the same registration_number are queued and handled sequentially.
-- Scheduled job poll query:
--   SELECT rr.*
--   FROM registration_requests rr
--   INNER JOIN (
--       SELECT registration_number,
--              MIN(created_at) AS min_created_at
--       FROM registration_requests
--       WHERE status_code = 'PENDING'
--       GROUP BY registration_number
--   ) oldest
--       ON rr.registration_number = oldest.registration_number
--      AND rr.created_at = oldest.min_created_at
--   WHERE rr.status_code = 'PENDING'
--   ORDER BY rr.created_at ASC;
CREATE INDEX idx_registration_requests_pending_reg_created
    ON registration_requests (registration_number, created_at)
    WHERE status_code = 'PENDING';

CREATE TABLE registration_request_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_request_id BIGINT NOT NULL,
    status_code VARCHAR(32) NOT NULL,
    error_message VARCHAR(2000),
    changed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_registration_request_status_history_request
        FOREIGN KEY (registration_request_id) REFERENCES registration_requests (id),
    CONSTRAINT fk_registration_request_status_history_status
        FOREIGN KEY (status_code) REFERENCES registration_request_statuses (code)
);
-- registration request related tables --