-- Company registration schema
-- Compatible with H2; adjust types/syntax for PostgreSQL, MySQL, etc. as needed.

CREATE TABLE clients (
    client_id VARCHAR(255) NOT NULL PRIMARY KEY,
    api_key VARCHAR(255) NOT NULL,
    CONSTRAINT uk_clients_api_key UNIQUE (api_key)
);

CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_number VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uk_companies_registration_number UNIQUE (registration_number)
);

CREATE TABLE registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR(255) NOT NULL,
    registration_number VARCHAR(255) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    status VARCHAR(32) NOT NULL,
    company_id BIGINT,
    error_message VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_registration_requests_company
        FOREIGN KEY (company_id) REFERENCES companies (id)
);
